# vim: set expandtab:

name: python-3.6-runtime
on: push
jobs:
  build:
    name: python-3.6-runtime
    runs-on: ubuntu-latest
    steps:
      - id: show_ref
        run: echo "Workflow is $GITHUB_REF"
      - id: show_workflow
        env:
          WORKFLOW: ${{ github.workflow }}
        run: echo "Workflow is $WORKFLOW aka ${GITHUB_WORKFLOW}"
      - id: prep
        name: Prepare build
        run: echo "::set-output name=tags::ghcr.io/${GITHUB_REPOSITORY_OWNER}/${GITHUB_WORKFLOW}:${GITHUB_REF}-${GITHUB_RUN_NUMBER}"
      - id: show_release
        env:
          RELEASE: ${{ github.run_number }}
        run: echo "Release is $RELEASE"
      - uses: docker/setup-qemu-action@v1
      - id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        needs: prep
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
