name: ci
on: push
jobs:
  build:
    name: python-3.6-runtime
    runs-on: ubuntu-latest
    steps:
#     - id: prep
#       if: "startsWith(github.ref, 'refs/tags/v')"
#       run: |
#         echo ::set-output name=tags::ghcr.io/okirch/python-3.6-runtime:${GITHUB_REF#refs/tags/v}
      - uses: docker/setup-qemu-action@v1
      - id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          push: true
          tags: python-3.6-runtime:latest
#       file: ./docker/image/app/Dockerfile
